name: Node.js Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  run-node-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          sudo apt-get install -y curl unzip
          curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.19.3/protoc-3.19.3-linux-x86_64.zip
          sudo unzip -o protoc-3.19.3-linux-x86_64.zip -d /usr/local bin/protoc
          sudo unzip -o protoc-3.19.3-linux-x86_64.zip -d /usr/local 'include/*'
          sudo chmod +x /usr/local/bin/protoc

      # Set up local dependencies
      - name: Setup for dependency `munkey-rpc`
        working-directory: ./lib/munkey-rpc
        run: npm pack

      # Install local dependencies
      - name: Install local dependencies
        working-directory: ./munkey
        run: |
          npm install --save --no-audit ../lib/munkey-rpc/munkey-munkey-rpc-0.0.1.tgz

      # Run tests for main package
      - name: Run tests for `munkey` service
        working-directory: ./munkey
        run: |
          npm install
          npm run test
  run-cli-tests:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build & setup CLI app/tests
      run: |
        dotnet restore
        dotnet build -c Release --no-restore
    - name: Run .NET command-line app tests
      run: |
        dotnet test -c Release --no-build
