name: Node.js Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  run-node-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install system dependencies
        run: sudo apt-get -y install protobuf-compiler

      # Set up local dependencies
      - name: Setup for dependency `munkey-rpc`
        working-directory: ./lib/munkey-rpc
        run: npm pack

      # Install local dependencies
      - name: Install local dependencies
        working-directory: ./munkey
        run: |
          npm install --save --no-audit ../lib/munkey-rpc/munkey-munkey-rpc-0.0.1.tgz

      # Run tests for main package
      - name: Run tests for `munkey` service
        working-directory: ./munkey
        run: |
          npm install
          npm run test
